apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-hack-fe
  labels:
    app: lambda-hack-fe
  namespace: karnot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lambda-hack-fe
  template:
    metadata:
      labels:
        app: lambda-hack-fe
    spec:
      containers:
        - name: main-container
          image: public.ecr.aws/o5q6k5w4/lambda-hack-fe:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: lambda-hack-fe-env