apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lambda-hack-fe-ingress
  namespace: karnot
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: >-
      arn:aws:acm:us-west-1:025097458243:certificate/bc734189-d4a5-4a12-8dea-7d0b5b92e4b0
    alb.ingress.kubernetes.io/group.name: orchestration-engine-ingress
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/actions.ssl-redirect":"443","alb.ingress.kubernetes.io/certificate-arn":"arn:aws:acm:us-west-1:025097458243:certificate/bc734189-d4a5-4a12-8dea-7d0b5b92e4b0","alb.ingress.kubernetes.io/group.name":"orchestration-engine-ingress","alb.ingress.kubernetes.io/listen-ports":"[{\"HTTP\":
      80},
      {\"HTTPS\":443}]","alb.ingress.kubernetes.io/scheme":"internet-facing","alb.ingress.kubernetes.io/target-type":"ip","kubernetes.io/ingress.class":"alb"},"name":"lambda-hack-fe-ingress","namespace":"karnot"},"spec":{"rules":[{"http":{"paths":[{"backend":{"service":{"name":"lambda-hack-fe-svc","port":{"number":3000}}},"path":"/","pathType":"Prefix"}]}}]}}
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - host: zkminer.karnot.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lambda-hack-fe-svc
                port:
                  number: 3000
