[package]
name = "bounty_ml"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.6.0" }
aligned-sdk = { git = "https://github.com/yetanotherco/aligned_layer" }
clap = "4.5.8"
