[workspace]
[package]
version = "0.1.0"
name = "quiz_implementation"
edition = "2021"

[dependencies]
alloy-sol-types = "0.7.2"
rand = "0.8.5"
serde = "1.0.203"
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", tag = "v1.0.7-testnet" }
